--Creación de tablas

USE metro_cdmx;

CREATE TABLE metro_cdmx.lines ( 
	id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,

	name VARCHAR(10) NOT NULL,
	color VARCHAR(15) NOT NULL,

	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY (id)
)
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;

CREATE TABLE metro_cdmx.trains(
	serial_number VARCHAR(10) NOT NULL,
	line_id BIGINT(20) UNSIGNED NOT NULL,

	type TINYINT(4) NOT NULL,
	year YEAR NOT NULL,
	
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY (serial_number),
	CONSTRAINT trains_line_id_foreign
	FOREIGN KEY (line_id) REFERENCES metro_cdmx.lines(id) 
)
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;


CREATE TABLE metro_cdmx.stations(
	id BIGINT(20) NOT NULL AUTO_INCREMENT,

	name VARCHAR(20) NOT NULL,

	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY (id)
)
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;

