#Código para crear la base de datos del proyecto PlaztiBlog

CREATE SCHEMA Platziblog;

CREATE TABLE categorias (id INTEGER NOT NULL AUTO_INCREMENT, nombre_categoria VARCHAR(20) NOT NULL,
PRIMARY KEY(id));

CREATE TABLE etiquetas (id INTEGER NOT NULL AUTO_INCREMENT, nombre_etiqueta VARCHAR(20) NOT NULL,
PRIMARY KEY(id));

CREATE TABLE usuarios (id INTEGER NOT NULL AUTO_INCREMENT, login VARCHAR(30) NOT NULL,
pass_word VARCHAR(20) NOT NULL, nickname VARCHAR(20) NOT NULL UNIQUE, 
email VARCHAR(50) NOT NULL UNIQUE, PRIMARY KEY(id));

CREATE TABLE posts (id INTEGER NOT NULL AUTO_INCREMENT, titulo VARCHAR(100) NOT NULL,
fecha_publicacion TIMESTAMP, contenido TEXT NOT NULL, estado CHAR(8) DEFAULT 'activo',
usuario_id INTEGER NOT NULL, categoria_id INTEGER NOT NULL, PRIMARY KEY(id),
FOREIGN KEY(usuario_id) REFERENCES Platziblog.usuarios(id) ON UPDATE CASCADE ON DELETE NO ACTION,
FOREIGN KEY(categoria_id) REFERENCES Platziblog.categorias(id) ON UPDATE CASCADE ON DELETE NO ACTION);

CREATE TABLE comentarios (id INTEGER NOT NULL AUTO_INCREMENT, fecha_publicacion TIMESTAMP,
contenido TEXT NOT NULL, usuario_id INTEGER NOT NULL, post_id INTEGER NOT NULL, PRIMARY KEY(id),
FOREIGN KEY(usuario_id) REFERENCES Platziblog.usuarios(id) ON UPDATE CASCADE ON DELETE NO ACTION,
FOREIGN KEY(post_id) REFERENCES Platziblog.posts(id) ON UPDATE CASCADE ON DELETE NO ACTION);

CREATE TABLE posts_etiquetas (id INTEGER NOT NULL AUTO_INCREMENT, post_id INTEGER NOT NULL,
etiqueta_id INTEGER NOT NULL, PRIMARY KEY(ID),
FOREIGN KEY(post_id) REFERENCES Platziblog.posts(id) ON UPDATE CASCADE ON DELETE NO ACTION,
FOREIGN KEY(etiqueta_id) REFERENCES Platziblog.etiquetas(id) ON UPDATE CASCADE ON DELETE NO ACTION); 
